bot/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


app_name = 'bot'

urlpatterns = [
    path('', csrf_exempt(views.Bot.as_view()), name='bot'),
]

cards/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


app_name = 'cards'

urlpatterns = [
    path('cards', views.Card.as_view(), name='cards'),
    path('add/', views.AddNewCard.as_view(), name='add'),
    path('edit-card/<int:id>', views.CardEdit.as_view(), name='edit-card'),
    path('delete-card/<int:id>', views.CardDelete.as_view(), name='delete-card'),
    path('how-to/', views.how_to, name='how-to'),
]

dateapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cards/', include('cards.urls', namespace='cards')),
    path('bot/', include('bot.urls', namespace='bot')),
    path('information', views.information, name='information'),
    path('policy', views.policy, name='policy'),
    path(
        "profile-deleted",
        views.profile_deleted, name="profile-deleted"),
]

cards/models.py
from django.db import models
from django.contrib.auth.models import User


class Cards(models.Model):
    SEX_MALE = 1
    SEX_FEMALE = 2

    SEX_CHOICES = [
        (SEX_MALE, 'Мужчина'),
        (SEX_FEMALE, 'Женщина')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cards")
    birthdate = models.DateField(blank=False, null=False)
    friend_name = models.CharField('friend_name', max_length=255, blank=False, null=False)
    info = models.CharField('information', max_length=255, blank=True, null=True)
    sex = models.IntegerField(
        "Пол", choices=SEX_CHOICES, default=SEX_MALE
    )

    def __str__(self):
        return "Карточка друга %s" % self.user.username

    # To create db when user created
    # def create_profile(sender, **kwargs):
    #     if kwargs['created']:
    #         Cards.objects.create(user=kwargs['instance'])
    # models.signals.post_save.connect(create_profile, sender=User)

cards/forms.py
from django import forms

from cards.models import Cards


class AddCard(forms.ModelForm):
    class Meta:
        model = Cards
        fields = ("friend_name", "birthdate", "info", "sex")
        labels = {
            "friend_name": 'Имя друга',
            "birthdate": 'Дата рождения',
            "info": 'Информация',
        }

cards/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from cards.forms import AddCard
from cards.models import Cards


class Card(LoginRequiredMixin, ListView):
    """ Load cards list"""
    model = Cards
    context_object_name = "cards"
    template_name = "cards.html"

    def get_queryset(self):
        u = self.request.user
        qs = super().get_queryset()
        return qs.filter(user=u)


class AddNewCard(LoginRequiredMixin, View):
    """ Add new card """
    def post(self, request, *args, **kwargs):
        form = AddCard(request.POST)
        if form.is_valid():
            new_friend = form.save(commit=False)
            new_friend.user = request.user
            new_friend.save()
            return redirect(reverse("cards:cards"))

        return render(request, "cards/add.html", {"form": form})

    def get(self, request, *args, **kwargs):
        form = AddCard()
        return render(request, "cards/add.html", {"form": form})


class CardEdit(LoginRequiredMixin, View):
    """ Edit cards """
    def post(self, request, id, *args, **kwargs):
        card = Cards.objects.get(id=id)
        form = AddCard(request.POST, instance=card)
        if form.is_valid():
            card_edit = form.save(commit=False)
            card_edit.owner = request.user
            card_edit.save()
            return redirect(reverse("cards:cards"))

        return render(request, "cards/edit-card.html", {"form": form})

    def get(self, request, id, *args, **kwargs):
        card = Cards.objects.get(id=id)
        form = AddCard(instance=card)
        return render(
            request, "cards/edit-card.html", {"form": form, "card": card})


class CardDelete(LoginRequiredMixin, View):
    """ Delete cards """
    def get(self, request, id):
        card = Cards.objects.get(id=id)
        card.delete()
        return redirect(reverse("cards:cards"))


def how_to(request):
    return render(request, 'cards/how-to.html')

cards/templates/cards/add.html
{% extends "base.html" %}
{% block title %}Новая карточка{% endblock %}
{% block main %}
  <h1>Добавить новую карточку</h1>
  <p>Используйте форму ниже чтобы добавить новую карточку:</p>
    {% load crispy_forms_tags %}
  <form action="{% url "cards:add" %}" method="post">
    {{ form | crispy }}
    {% csrf_token %}
<button type="submit" class="btn btn-success">Сохранить</button>
  </form>
  </form>
{% endblock %}

cards/templates/cards/edit-card.html
{% extends "base.html" %}
{% block title %}Изменить карточку{% endblock %}

{% block main %}
  <h1>Изменить карточку</h1>
{% load crispy_forms_tags %}
  <form action="{% url "cards:edit-card" card.pk %}" method="post">
{% csrf_token %}
{{ form | crispy }}
    <button type="submit" class="btn btn-success">Сохранить</button>
  </form>
{% endblock %}

cards/templates/cards/how-to.html
{% extends "base.html" %}

{% block title %}Как пользоваться приложением?{% endblock %}

{% block main %}
<div class="row" style="padding-top: 1.2em">
     <div class="col">
  <h1>Как пользоваться приложением?</h1>
  <div class="col" style="margin-top: 20px">
<iframe width="300" height="315" src="https://www.youtube.com/embed/cw5GAnGj5Gk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>

  <hr>
  <div style="margin-top: 50px">
  <h3 style="text-align: center; padding-top: 20px;">Контактная информация</h2>
    <p>Чтобы задать вопрос, высказать пожелние или внести предложение, пишите в телеграм:<br> @glebrulev</p>
    <hr style="margin-top: 30px">
</div>
</div>


{% endblock %}