accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('menu/', views.menu, name='menu'),

    path(
        'password-change/',
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        'password-change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),


    path("pwd-reset/",
         auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path(
        "pwd-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done"
    ),
    path(
        "pwd-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "pwd-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete"
    ),
    path(
        "delete-profile/",
        views.DeleteProfile.as_view(), name="delete-profile"),
]

bot/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


app_name = 'bot'

urlpatterns = [
    path('', csrf_exempt(views.Bot.as_view()), name='bot'),
]

dateapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cards/', include('cards.urls', namespace='cards')),
    path('bot/', include('bot.urls', namespace='bot')),
    path('information', views.information, name='information'),
    path('policy', views.policy, name='policy'),
    path(
        "profile-deleted",
        views.profile_deleted, name="profile-deleted"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField(blank=True, null=True)
    telegram = models.CharField('telegram', max_length=64, blank=True, null=True)
    messenger = models.CharField('messenger', max_length=255, blank=True, null=True)
    phone_number = models.CharField('phone_number', max_length=64, blank=True, null=True)

    def __str__(self):
        return "Профиль пользователя %s" % self.user.username

    def create_profile(sender, **kwargs):
        """
        Create db when user is register
        """
        if kwargs['created']:
            Profile.objects.create(user=kwargs['instance'])
    models.signals.post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from accounts.models import Profile


class RegistrationFormUniqueEmail(forms.ModelForm):
    """ Registration form """
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "email")
        labels = ('Имя пользователя', "Ваше имя и фамилия", "Адрес электронной почты")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Пароли не совпадают")
        return cd["password2"]


class LoginForm(forms.Form):
    """ Login form """
    username = forms.CharField(label='Логин')
    password = forms.CharField(widget=forms.PasswordInput)


class UserEditForm(forms.ModelForm):
    """ Edit user-db form """
    class Meta:
        model = User
        fields = ("first_name", "email")


class ProfileEditForm(forms.ModelForm):
    """ Edit progile-db form """
    class Meta:
        model = Profile
        fields = ("birthdate",)
        labels = {
            "birthdate": 'Дата рождения'
        }

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

from accounts.forms import RegistrationFormUniqueEmail, LoginForm, UserEditForm, ProfileEditForm


class LoginView(View):
    """ Login """
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd["username"], password=cd["password"]
            )
            if user is None:
                return HttpResponse("Invalid login")

            if not user.is_active:
                return HttpResponse("Disabled account")

            login(request, user)
            messages.success(request, "Добро пожаловать, вы зарегистрированы")
            return HttpResponse("Welcome! Authenticated successfully")
        else:
            return render(request, "accounts/login.html", {"form": form})

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, "accounts/login.html", {"form": form})


def register(request):
    """ User registration """
    if request.method == "POST":
        form = RegistrationFormUniqueEmail(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()

            return render(
                request, "accounts/registration_complete.html",
                {"new_user": new_user}
            )
    else:
        form = RegistrationFormUniqueEmail()

    return render(request, "accounts/register.html", {"user_form": form})


@login_required
def profile(request):
    """ Get user-profile page"""
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile, data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Профиль изменен")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(
        request,
        "accounts/edit.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


@login_required
def menu(request):
    return render(request, 'menu.html')


class DeleteProfile(View):
    """ Delete profile """
    def post(self, request, *args, **kwargs):
        user = request.user
        profile = User.objects.filter(id=user.id)
        profile.delete()
        return render(request, "profile-deleted.html")

    def get(self, request, *args, **kwargs):
        return render(request, "accounts/delete-profile.html")

accounts/templates/accounts/delete-profile.html
{% extends "base.html" %}
{% block title %} Профиль {% endblock %}
{% block main %}
<h1>Вы точно хотите удалить аккаунт?</h1>
<form action="." method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<button style="width:120px; height:40px;
     margin-bottom: 10px; margin-top:10px; font-size: 18px" type="submit" class="btn btn-success">Удалить аккаунт?</button>
</form>
<p><a href="{% url "accounts:menu" %}">Вернуться в главное меню</a></p>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends "base.html" %}
{% block title %} Профиль {% endblock %}
{% block main %}
  <h1>Личный кабинет</h1>
  <p>Используйте форму ниже чтобы что-то поменять в профиле:</p>
    {% load crispy_forms_tags %}
  <form action="." method="post" enctype="multipart/form-data">
    {{ user_form | crispy }}
    {{ profile_form | crispy }}
    {% csrf_token %}
    <button style="width:120px; height:40px;
     margin-bottom: 10px; font-size: 18px" type="submit" class="btn btn-success">Сохранить</button>
  </form>
    <p><a href="{% url "accounts:password_change" %}">Поменять пароль</a></p>
    <p><a href="{% url "accounts:delete-profile" %}">Удалить аккаунт</a></p>

  </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block main %}
  {% block side_bar %}
{% if user.is_authenticated %}

<div class="side_bar col">
    <p>Login: {{ user.username }}</p>
    <a href="{% url "accounts:edit" %}">Добавить инфу</a>
    <a href="{% url "accounts:password_change" %}">Поменять пароль</a>

</div>
{% endif %}
{% endblock %}

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Зарегистрироваться{% endblock %}
{% block main %}
<h1>Создать аккаунт</h1>
<p>Воспользуйтесь следующей формой:</p>
{% load crispy_forms_tags %}
<form action="." method="post" class="register">
{{ user_form | crispy }}
{% csrf_token %}
<button style="width:120px; height:40px;
     margin-bottom: 10px; font-size: 18px" type="submit" class="btn btn-success">Создать</button>
</form>
<p style="margin-top: 15px; font-size: 1.1rem"><a href="{% url "accounts:login" %}">Уже есть аккаунт?</a></p>
{% endblock %}

accounts/templates/accounts/registration_complete.html
<{% extends "base.html" %}

{% block title %}Ура! Успех{% endblock %}
{% block main %}
<h1>Всё готово, {{ new_user.first_name }}!</h1>
<p>Ваш аккаунт был создан, теперь можно <a href="{% url "accounts:login" %}">залогиниться</a>.</p>

{% endblock %}