accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('menu/', views.menu, name='menu'),

    path(
        'password-change/',
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        'password-change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),


    path("pwd-reset/",
         auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path(
        "pwd-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done"
    ),
    path(
        "pwd-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "pwd-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete"
    ),
    path(
        "delete-profile/",
        views.DeleteProfile.as_view(), name="delete-profile"),
]

bot/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


app_name = 'bot'

urlpatterns = [
    path('', csrf_exempt(views.Bot.as_view()), name='bot'),
]

cards/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


app_name = 'cards'

urlpatterns = [
    path('cards', views.Card.as_view(), name='cards'),
    path('add/', views.AddNewCard.as_view(), name='add'),
    path('edit-card/<int:id>', views.CardEdit.as_view(), name='edit-card'),
    path('delete-card/<int:id>', views.CardDelete.as_view(), name='delete-card'),
    path('how-to/', views.how_to, name='how-to'),
]

dateapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cards/', include('cards.urls', namespace='cards')),
    path('bot/', include('bot.urls', namespace='bot')),
    path('information', views.information, name='information'),
    path('policy', views.policy, name='policy'),
    path(
        "profile-deleted",
        views.profile_deleted, name="profile-deleted"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
  <head lang="ru">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}DATEAPP{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-ligh" style="border-bottom: 1px solid #ebeaeb">
        <a href="/"><img src="{% static "img/logo1.png" %}" style="width: 5.9rem; margin: 0 15px 0 35px;" alt="Logo"/></a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav mr-auto mt-2">
                        <li class="nav-item"><a style="font-size: 1.0rem;padding-right: 1.25rem;" class="nav-link" href="{% url "cards:add" %}">Добавить карточку</a></li>
                        <li class="nav-item"><a style="font-size: 1.0rem;padding-right: 1.25rem;" class="nav-link" href="{% url "cards:cards" %}">Мои карточки</a></li>
                        <li class="nav-item"><a style="font-size: 1.0rem;padding-right: 1.25rem;" class="nav-link" href="{% url "accounts:profile" %}">Мой профиль</a></li>
                        <li class="nav-item"><a style="font-size: 1.0rem;padding-right: 1.25rem;" class="nav-link" href="{% url "accounts:menu" %}">Меню</a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a style="font-size: 1rem" class="nav-link" href="{% url "accounts:logout" %}">Выйти</a></li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a style="font-size: 1rem" class="nav-link" href="{% url "accounts:register" %}">Регистрация</a></li>
                        <li class="nav-item"><a style="font-size: 1rem" class="nav-link" href="{% url "accounts:login" %}">Войти</a></li>
                    </ul>
                {% endif %}
            </div>
        </nav>
        {% if messages %}
              {% for message in messages %}
              <div class="alert alert-dismissible alert-{{ message.tags }}" style="text-align: center; margin-bottom: 0rem">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>{{ message|safe }}</strong>
              </div>
              {% endfor %}
          {% endif %}
        <main class="container p-5">
            {% block main %}{% endblock %}
        </main>

<footer class="small text-center text-muted" style="margin-bottom: 15px">
          <p style="font-size: 0.8rem"><a href="{% url "policy" %}">Политика конфиденциальности</a></p>
            Designed by Gleb Rulev
        </footer>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}DATEAPP{% endblock %}

{% block main %}
<div class="row" style="padding-top: 1.2em">
     <div class="col">
  <h1 style="text-align: center; font-weight: bold; font-size:3.3em">Все важные даты у тебя в телефоне</h1>
       <p style="text-align: center; font-size: 1.4em">Вноси дни рождения близких людей и
           получай напоминания по почте или в телеграме</p>
         <div style="margin-top: 30px;">
             <a style="width:220px;height:55px;
  margin-bottom: 10px; font-size: 19px; padding: 0.8rem 0.5rem;" class="btn btn-outline-success" href="http://dateapp.fun/information">Подробнее</a>
             <a style="width:220px;height:55px;
  margin-bottom: 10px; font-size: 19px; padding: 0.8rem 0.5rem;" class="btn btn-success" href="{% url "accounts:register" %}">Регистрация</a>
         </div>
         </div>
 <div class="col" style="margin-top: 20px">
<iframe width="250" height="315" src="https://www.youtube.com/embed/cw5GAnGj5Gk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>
<div style="margin-top: 50px">
  <hr>
  <h3 style="text-align: center; padding-top: 20px;">Контактная информация</h2>
    <p>Чтобы задать вопрос, высказать пожелание или внести предложение, пишите в телеграм:<br> @glebrulev</p>
    <hr style="margin-top: 30px">
</div>


{% endblock %}

templates/information.html
{% extends "base.html" %}

{% block title %}Подробнее{% endblock %}
{% block main %}
{% load static %}
<h1>Как это работает?</h1>
<div class="row" style="padding-top: 1.2em">
     <div class="col" style="flex-basis: auto;">
       <p style="text-align: center; font-size: 1.9rem; padding-top: 10px; padding-bottom: 10px;">1. Вноси дни рождения близких людей в приложениe.</p>
         </div>
  <div class="col">
  	<img style="width: 15rem; border: 0.1px solid grey; border-radius: 17px; box-shadow: 0 0 10px rgba(0,0,0,0.5)" src="{% static "img/cards4.jpg" %}"/>
  </div>
</div>
<div class="row" style="padding-top: 1.2em">
     <div class="col" style="flex-basis: auto;">
       <p style="text-align: center; font-size: 1.9rem; padding-top: 10px; padding-bottom: 10px;">2. Получай уведомление по почте и в телеграм</p>
         </div>
  <div class="col" style="flex-basis: auto;">
  	<img style="width: 15rem; border: 0.1px solid grey; border-radius: 17px; box-shadow: 0 0 10px rgba(0,0,0,0.5)" src="{% static "img/bot1.jpg" %}"/>
  </div>
  <div class="col" style="flex-basis: auto;">
  	<img style="margin-top: 1.2em;width: 15rem; border: 0.1px solid grey; border-radius: 17px; box-shadow: 0 0 10px rgba(0,0,0,0.5)" src="{% static "img/mail.jpg" %}"/>
  </div>
  <div class="col" style="flex-basis: auto; padding-top: 1.2em">
  	<p>Уведомления будут приходить:</p>
  <p>- В начале месяца <br>
  	- В начале недели<br>
  	- Каждый день
  </p>
</div>
</div>
<div class="row" style="padding-top: 1.2em">
     <div class="col" style="flex-basis: auto;">
       <p style="text-align: center; font-size: 1.9rem; padding-top: 10px; padding-bottom: 10px;">3. Как начать пользоваться приложением?</p>
       <p>Приложение абсолютно бесплатное и доступно любому у кого есть электронная почта и телеграм.<br>
       Чтобы начать пользоваться приложением вам нужно зарегистрироваться на сайте и активировать телеграм-бота</p>
     </div>
     <div class="col" style="flex-basis: auto;">
     	<a style="width:140px;height:50px;
  margin-bottom: 10px; font-size: 19px; padding: 0.8rem 0.5rem;" class="btn btn-success" href="{% url "accounts:register" %}">Регистрация</a>
     </div>
</div>
{% endblock %}

templates/menu.html
{% extends "base.html" %}
{% block title %} Профиль {% endblock %}
{% block main %}
  <h1 style="margin-bottom: 45px">Главное меню</h1>
<div class="btn-group-vertical">
    <a href="{% url "cards:add" %}" style="margin-bottom: 15px" class="btn btn-success btn-lg">Добавить карточку</a>
<a href="{%url "cards:cards" %}" style="margin-bottom: 15px" class="btn btn-info btn-lg">Мои карточки</a>
<a href="{% url "accounts:profile" %}" style="margin-bottom: 15px" class="btn btn-warning btn-lg">Личный кабинет</a>
</div>
<p style="margin-top: 15px; font-size: 1.1rem"><a href="{% url "cards:how-to" %}">Как пользоваться приложением?</a></p>
<p style="margin-top: 15px; font-size: 1.1rem"><a href="https://t.me/datebestappbot">Активировать бота</a></p>

{% endblock %}

templates/policy.html
{% extends "base.html" %}
{% block title %} Политика конфиденциальности {% endblock %}
{% block main %}
<h1>Политика конфиденциальности</h1>
<h2>Общий доступ к данным</h2>
<p>Мы не предоставляем доступа к Вашим личным данным. Никому и никогда</p>
<h3>Хранение данных</h3>
<p>Dateapp хранит только те данные, которые необходимы для корректного функционирования — до тех пор, пока Вы пользуетесь Dateapp.</p>
<h4>Удаление данных</h4>
<p>Если Вы хотите удалить свой аккаунт, пожалуйста, зайдите в аккаунт, нажмите "Мой профиль"/"Личный кабинет" и удалите аккаунт. Удаление аккаунта повлечет за собой удаление всех данных. Это действие не может быть отменено.</p>
{% endblock %}

templates/profile-deleted.html
{% extends "base.html" %}
{% block title %} Профиль удален {% endblock %}
{% block main %}
<h1>Ваш аккаунт удален </h1>
<p>Все данные, связанные с аккаунтом так же удалены</p>
{% endblock %}